# Generated by Django 5.2.5 on 2025-08-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photo')),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_desg', models.CharField(max_length=150)),
                ('emp_exp', models.IntegerField()),
            ],
        ),
    ]
