# Generated by Django 5.2.5 on 2025-08-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surve_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ourservices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='Emp_services')),
                ('title', models.CharField(max_length=300)),
                ('descr', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='employee_db',
            name='image',
            field=models.ImageField(upload_to='Emp_photo'),
        ),
    ]
